### ISSUE TITLE
On the win or loss screens you cannot go backwards.

### ISSUE THREAD

**Issue by Aidyl98** [Root-101/citmatel_strawberry_hangman#12]
When the user is in the win or lose screen, right now this one can press back and enter in the sublevel screen again. The correct behavior is that when back is pressed the user go to the level or menu screen.

**Comment by JesusHdezWaterloo** [comment]
Cambiada la navegación para:
````dart
  void _looseLevel() {
    Get.offNamed(HangManSubLevelLose.ROUTE_NAME);
  }
```
