### ISSUE TITLE
Quickly taps on the keyboard, make the win and lose screen play at the same time.

### ISSUE THREAD

**Issue by Aidyl98** [Root-101/citmatel_strawberry_hangman#16]
Implement that when the level is won or lost, the keyboard is deactivated, or it does not allow you to touch more elements. 

When there is only one heart and one letter left to complete, the user quickly taps one right letter and one wrong letter and both the win and lose screens are played.

**Comment by JesusHdezWaterloo** [comment]
Agregada validación cuando se gana.
Agregarla tambien cuando se pierde.

**Comment by JesusHdezWaterloo** [comment]
Agregada la validacion para cuando se pierde.
Usa solucion alternatica es en el onLoose o onWin hacerle el dispose al controller con `super.dispose()`, asi si se ejecuta otra accion, en este caso sobre un controller destruido se ignorará la llamada
