### ISSUE TITLE
Inconsistencia en el tutorial

### ISSUE THREAD

**Issue by JesusHdezWaterloo** [Root-101/citmatel_strawberry_hangman#20]
- [X] Al perder una vida en el subnivel 4 sale el tutorial, cuando solo debe salir en el subnivel 1
- [x] Si se le da atras en pleno tutorial sale a la pantalla de los niveles con ese tutorial activo, así:
![imagen](https://user-images.githubusercontent.com/47437879/150608554-2b7344d1-4aff-4e86-bbe9-f57bc2ac2e35.png)

**Comment by JesusHdezWaterloo** [comment]
Ya se validó por @Aidyl98 que solo salga el tutorial en el sub nivel 1 del nivel 1

**Comment by Aidyl98** [comment]
A `TutorialCoachMark `object was created and then the function `finish()` whas call in the `dispose()`.
