### ISSUE TITLE
Poner en gris y disable la letra cuando se selecciona

### ISSUE THREAD

**Issue by JesusHdezWaterloo** [Root-101/citmatel_strawberry_hangman#5]
Al seleccionar una letra, da igual que esté bien o mal, se tiene que poner gris para no seleccionarla de nuevo
Tan sencillo como tener una lista en el controller con todas las letras que se han tocado y pintar en consecuencia.
La lógica de la lista va en el UC

**Comment by JesusHdezWaterloo** [comment]
En la logica cuando se llama al `checkLetter(String letter)` del UC, este marca la letra como usada y devuelve las posiciones.
Si la letra existe y devuelve una lista con las posiciones todo ok, porque la visual pone de nuevo las letras en su posicion y no pasa nada. Sin embargo, si la palabra no contiene la letra y ya está usada, se vulve a perder una vida, que creo que no debería ser, por lo tanto hay que validar eso, pero como las vidas se controlan en el controller es ahi donde va la validación.
Por lo tanto debería ser algo como:
```dart
  void checkLetter(String letter) {
    List<int> possiblesIndex = subLevelUseCase.checkLetter(letter);
    if (possiblesIndex.isEmpty && !subLevelUseCase.isUsed(letter)) {//aqui agregar el !isUsed, o sea, si no existe la letra en la palabra, y NO HE USADO la letra, entonces pierdo un corazón, de lo contrario relleno las letras y ya
      //no existe esa letra en la palabra
      _breakHeart();
    } else {
      _fillAnswer(possiblesIndex, letter);
    }
    update();
  }
```

**Comment by JesusHdezWaterloo** [comment]
Agregé ya en el Controller el delegate al isUsed

**Comment by Aidyl98** [comment]
When the keyboard visual is created, it is checked if the letter is in use, with the isUsed method. If it has already been used, the card is drawn in gray and the onTap is disabled.

` controller.isUsed(listOfLetters[index])
                ? _emptyCard(
                    listOfLetters[index],
                    Colors.grey.shade500,
                    Colors.transparent,
                  )
                : InkWell(
                    child: _emptyCard(
                      listOfLetters[index],
                      Colors.white,
                      Colors.grey.shade700,
                    ),
                    onTap: () => controller.checkLetter(listOfLetters[index]),
                  ), `

**Comment by Aidyl98** [comment]
When the keyboard visual is created, it is checked if the letter is in use, with the isUsed method. If it has already been used, the card is drawn in gray and the onTap is disabled.
```
 
controller.isUsed(listOfLetters[index])
                ? _emptyCard(
                    listOfLetters[index],
                    Colors.grey.shade500,
                    Colors.transparent,
                  )
                : InkWell(
                    child: _emptyCard(
                      listOfLetters[index],
                      Colors.white,
                      Colors.grey.shade700,
                    ),
                    onTap: () => controller.checkLetter(listOfLetters[index]),
                  ),```
