### ISSUE TITLE
Smooth Transition on check letter

### ISSUE THREAD

**Issue by JesusHdezWaterloo** [Root-101/citmatel_strawberry_hangman#7]
Al seleccionar una letra o bien se pierde un corazón, o se pone una letra en la respuesta, animar esos efectos

**Comment by Aidyl98** [comment]
Animated the effects by using the 

> flutter_animator package: 
^ 3.2.0

**Comment by Aidyl98** [comment]
Animated the effects by using:

> flutter_animator package: ^ 3.2.0
